4559jacky/film_log

film_log/src/main/java/com/filmlog/common/filter/EncodingFilter.java
film_log/src/main/java/com/filmlog/common/filter/EncryptFilter.java
film_log/src/main/java/com/filmlog/common/filter/PassWordEncodingWrapper.java
film_log/src/main/java/com/filmlog/member/controller/MemberCreateServlet.java
film_log/src/main/java/com/filmlog/member/controller/MemberLoginServlet.java
film_log/src/main/java/com/filmlog/member/model/dao/MemberDao.java
film_log/src/main/java/com/filmlog/member/model/service/MemberService.java
film_log/src/main/java/com/filmlog/member/model/vo/Member.java
film_log/src/main/resources/mappers/member-mapper.xml
film_log/src/main/resources/mybatis-config.xml
film_log/src/main/webapp/views/include/nav.jsp
film_log/src/main/webapp/views/member/login.jsp

- 세션에 따라 관리자 페이지, 마이 페이지, 로그인으로 뜨도록 로직 변경

[jji] 로그인 암호화 기능 생성 및 nav.jsp수정

---

film_log/src/main/java/com/filmlog/movie/controller/MovieApiServlet.java
film_log/src/main/java/com/filmlog/movie/controller/MovieCreateServlet.java
film_log/src/main/java/com/filmlog/movie/controller/MovieListServlet.java
film_log/src/main/java/com/filmlog/movie/model/dao/MovieDao.java
film_log/src/main/java/com/filmlog/movie/model/service/MovieService.java
film_log/src/main/java/com/filmlog/movie/model/vo/Movie.java
film_log/src/main/java/com/filmlog/movie/model/vo/MovieDTO.java
film_log/src/main/resources/mappers/movie-mapper.xml
film_log/src/main/webapp/views/movie/create.jsp
film_log/src/main/webapp/views/movie/list.jsp

[psb] API 영화정보 가지고 오는 코드 작성 및 DB에 insert하는 코드 작성중

---

film_log/src/main/java/com/filmlog/qna/controller/DeleteQnaServlet.java
film_log/src/main/java/com/filmlog/qna/controller/UpdateQnaPassServlet.java
film_log/src/main/java/com/filmlog/qna/controller/UpdateQnaServlet.java
film_log/src/main/java/com/filmlog/qna/model/dao/QnaDao.java
film_log/src/main/java/com/filmlog/qna/model/service/QnaService.java
film_log/src/main/resources/mappers/qna-mapper.xml
film_log/src/main/webapp/views/qna/showQna.jsp
film_log/src/main/webapp/views/qna/updateQna.jsp

[jhs] QnA 사용자 부분 완료

---

film_log/src/main/java/com/filmlog/movie/model/vo/Genre.java

[PSB] vo.Genre 파일 commit

---

film_log/src/main/resources/mappers/movie-mapper.xml
film_log/src/main/resources/mybatis-config.xml

[PSB] mapper,mabatis commit

---

film_log/src/main/java/com/filmlog/qna/controller/DeleteResponseServlet.java
film_log/src/main/java/com/filmlog/qna/controller/InsertResponseServlet.java
film_log/src/main/java/com/filmlog/qna/controller/SelectOneQnaServlet.java
film_log/src/main/java/com/filmlog/qna/controller/UpdateResponseServlet.java
film_log/src/main/java/com/filmlog/qna/model/dao/QnaDao.java
film_log/src/main/java/com/filmlog/qna/model/service/QnaService.java
film_log/src/main/java/com/filmlog/qna/model/vo/Qna.java
film_log/src/main/resources/mappers/qna-mapper.xml
film_log/src/main/resources/mybatis-config.xml
film_log/src/main/webapp/resources/css/qna/showQna.css
film_log/src/main/webapp/resources/css/sideBar/sideBar.css
film_log/src/main/webapp/resources/js/sideBar/sideBar.js
film_log/src/main/webapp/views/include/nav.jsp
film_log/src/main/webapp/views/member/admin/admin.jsp
film_log/src/main/webapp/views/qna/showQna.jsp

[jhs] QnA 사용자, 관리자 페이지 1차 완료

---

film_log/src/main/java/com/filmlog/member/admin/controllor/SelectMovieListServlet.java
film_log/src/main/java/com/filmlog/member/admin/model/dao/AdminDao.java
film_log/src/main/java/com/filmlog/member/admin/model/service/AdminService.java
film_log/src/main/java/com/filmlog/member/admin/model/vo/Admin.java
film_log/src/main/webapp/views/include/nav.jsp

[psb] 관리자페이지 클래스 생성 commit

---

film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardDeleteServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardFilePathServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardInsertServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardListServlet.java
film_log/src/main/java/com/filmlog/reviewboard/model/dao/ReviewBoardDao.java
film_log/src/main/java/com/filmlog/reviewboard/model/service/ReviewBoardService.java
film_log/src/main/java/com/filmlog/reviewboard/model/vo/ReviewBoard.java
film_log/src/main/resources/mappers/reviewboard-mapper.xml
film_log/src/main/webapp/views/include/nav.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardDetail.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardInsert.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardList.jsp

[ysw] 게시글 출력 목록 페이지, 게시글 추가 페이지 css 추가 및 게시글 상세 조회 기능 구현 commit

[ysw] 게시글 출력 목록 페이지, 게시글 추가 페이지 css 추가 및 게시글 상세 조회 기능 구현 commit

---

film_log/src/main/java/com/filmlog/common/filter/EncryptFilter.java
film_log/src/main/java/com/filmlog/member/controller/DuplicateNicknameCheckServlet.java
film_log/src/main/java/com/filmlog/member/controller/MemberCreateServlet.java
film_log/src/main/java/com/filmlog/member/model/dao/MemberDao.java
film_log/src/main/java/com/filmlog/member/model/service/MemberService.java
film_log/src/main/java/com/filmlog/member/model/vo/Member.java
film_log/src/main/java/com/filmlog/movie/model/vo/Genre.java
film_log/src/main/resources/mappers/member-mapper.xml
film_log/src/main/webapp/views/include/nav.jsp
film_log/src/main/webapp/views/member/join/memberCreate.jsp

[jji] 회원가입 정규식, 속성값 불일치시 다음 속성입력으로 못넘어가게 구현 및 회원가입시 사용자 관심 장르 추가기능

[jji] 회원가입 정규식, 속성값 불일치시 다음 속성입력으로 못넘어가게 구현 및 회원가입시 사용자 관심 장르 추가기능

---

film_log/src/main/java/com/filmlog/common/filter/EncryptFilter.java
film_log/src/main/java/com/filmlog/member/controller/EncryptPwServlet.java
film_log/src/main/java/com/filmlog/member/controller/MemberCreateServlet.java
film_log/src/main/webapp/views/member/join/memberCreate.jsp

- formData에 담아서 보내서 암호화가 안걸리는 상황
- 비밀번호만 따로 받아서 암호화를 해주는 Servlet을 하나 더 만듦
- ajax에서 비밀번호를 잘 받아오면 다시 ajax를 추가해 formData를 넘겨서 회원정보 저장

[jji] 회원가입 비밀번호 암호화 오류 수정 commit

---

film_log/src/main/java/com/filmlog/common/filter/EncryptFilter.java
film_log/src/main/java/com/filmlog/member/controller/ChangePwdServlet.java
film_log/src/main/java/com/filmlog/member/controller/FindIdServlet.java
film_log/src/main/java/com/filmlog/member/controller/FindMemberForPwdServlet.java
film_log/src/main/java/com/filmlog/member/controller/Pass/ChangePwdPassServlet.java
film_log/src/main/java/com/filmlog/member/controller/Pass/FindIdPassServlet.java
film_log/src/main/java/com/filmlog/member/model/dao/MemberDao.java
film_log/src/main/java/com/filmlog/member/model/service/MemberService.java
film_log/src/main/resources/mappers/member-mapper.xml
film_log/src/main/webapp/views/member/find/changePwd.jsp
film_log/src/main/webapp/views/member/find/findId.jsp
film_log/src/main/webapp/views/member/join/memberCreate.jsp
film_log/src/main/webapp/views/member/login/login.jsp

- 아이디찾기에서 한 페이지에서 div를 나눠 정보를 입력하면 아이디를 보여줌
- 비밀번호 재설정 시 다시 암호화를 시켜서 저장

[jji] 아이디찾기 및 비밀번호 재설정 기능 구현 commit

---

film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardDeleteServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardFilePathServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardUpdatePassServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardUpdateServlet.java
film_log/src/main/java/com/filmlog/reviewboard/model/dao/ReviewBoardDao.java
film_log/src/main/java/com/filmlog/reviewboard/model/service/ReviewBoardService.java
film_log/src/main/resources/mappers/reviewboard-mapper.xml
film_log/src/main/webapp/views/reviewBoard/reviewBoardDetail.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardList.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardUpdate.jsp

[ysw] 게시글 삭체 처리 기능 구현, 게시글 수정 중간 commit

[ysw] 게시글 삭체 처리 기능 구현, 게시글 수정 중간 commit

---

film_log/src/main/java/com/filmlog/member/admin/controllor/SelectMyQnaListServlet.java
film_log/src/main/java/com/filmlog/member/admin/controllor/SelectQnaListServlet.java
film_log/src/main/java/com/filmlog/qna/model/dao/QnaDao.java
film_log/src/main/java/com/filmlog/qna/model/service/QnaService.java
film_log/src/main/java/com/filmlog/qna/model/vo/Qna.java
film_log/src/main/resources/mappers/qna-mapper.xml
film_log/src/main/webapp/resources/css/include/paing.css
film_log/src/main/webapp/views/include/nav.jsp
film_log/src/main/webapp/views/member/admin/qnaList.jsp
film_log/src/main/webapp/views/member/general/myQnaList.jsp
film_log/src/main/webapp/views/qna/showQna.jsp

[Jhs] QnA 구현 완료

---

film_log/src/main/java/com/filmlog/member/controller/ChangePwdServlet.java
film_log/src/main/java/com/filmlog/movie/controller/MovieApiServlet.java
film_log/src/main/java/com/filmlog/movie/model/dao/MovieDao.java
film_log/src/main/java/com/filmlog/movie/model/service/MovieService.java
film_log/src/main/java/com/filmlog/movie/model/vo/Genre.java
film_log/src/main/java/com/filmlog/movie/model/vo/MovieDTO.java
film_log/src/main/resources/mappers/movie-mapper.xml
film_log/src/main/resources/mybatis-config.xml

- id, title, original_title, overview, runtime, release_date, poster_path, adult

[jji] 영화 API 데이터 가져오기, 장르 매핑테이블에 각 영화의 장르 저장

---

film_log/src/main/java/com/filmlog/movie/controller/api/CastAndCrewApiServlet.java
film_log/src/main/java/com/filmlog/movie/controller/api/GenreApiServlet.java
film_log/src/main/java/com/filmlog/movie/controller/api/MovieApiServlet.java

[jji] movie controller에 api 패키지 추가 commit

[jji] movie controller에 api 패키지 추가 commit

---

film_log/src/main/java/com/filmlog/member/controller/MemberCreateServlet.java
film_log/src/main/webapp/views/member/join/memberCreate.jsp

회원가입시 이미지 추가 없을 시 기본이미지 추가 기능 구현

[jji] 회원가입시 이미지 추가 없을 시 기본이미지 추가 기능 구현

---

film_log/src/main/java/com/filmlog/common/filter/EncryptFilter.java
film_log/src/main/java/com/filmlog/member/controller/CheckPwdServlet.java
film_log/src/main/java/com/filmlog/member/controller/Pass/MemberPwdChangePassServlet.java
film_log/src/main/java/com/filmlog/member/model/dao/MemberDao.java
film_log/src/main/java/com/filmlog/member/model/service/MemberService.java
film_log/src/main/resources/mappers/member-mapper.xml
film_log/src/main/webapp/views/include/nav.jsp
film_log/src/main/webapp/views/member/my/myPwdChange.jsp

[jji] 개인정보 변경(비밀번호, 개인정보) 구현 commit

---

film_log/src/main/java/com/filmlog/movie/model/vo/MovieDTO.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardCommentDeleteServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardCommentInsertServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardDetailservlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardImgDeleteServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardInsertServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardListServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardUpdateServlet.java
film_log/src/main/java/com/filmlog/reviewboard/model/dao/ReviewBoardDao.java
film_log/src/main/java/com/filmlog/reviewboard/model/service/ReviewBoardService.java
film_log/src/main/java/com/filmlog/reviewboard/model/vo/ReviewBoard.java
film_log/src/main/java/com/filmlog/reviewboard/model/vo/ReviewBoardComment.java
film_log/src/main/resources/mappers/reviewboard-mapper.xml
film_log/src/main/webapp/views/reviewBoard/reviewBoardDetail.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardUpdate.jsp

[ysw] 댓글 전체 목록 조회, 추가 후 반영, 댓글 삭제 기능 구현 및 조회수 실시간 반영 commit

[ysw] 댓글 전체 목록 조회, 추가 후 반영, 댓글 삭제 기능 구현 및 조회수 실시간 반영 commit

---

film_log/src/main/java/com/filmlog/member/controller/MemberDeletePassServlet.java
film_log/src/main/java/com/filmlog/member/controller/MemberDeleteServlet.java
film_log/src/main/java/com/filmlog/member/model/dao/MemberDao.java
film_log/src/main/java/com/filmlog/member/model/service/MemberService.java
film_log/src/main/resources/mappers/member-mapper.xml
film_log/src/main/webapp/views/include/nav.jsp
film_log/src/main/webapp/views/member/my/deleteMember.jsp

[jji] 회원탈퇴 기능 구현 commit

---

film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardInsertServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardUpdateServlet.java
film_log/src/main/java/com/filmlog/reviewboard/model/service/ReviewBoardService.java
film_log/src/main/webapp/views/reviewBoard/reviewBoardUpdate.jsp

[ysw] 리뷰 게시판 수정 기능 구현 commit

---

film_log/src/main/java/com/filmlog/reviewboard/model/vo/ReviewBoard.java
film_log/src/main/resources/mappers/reviewboard-mapper.xml
film_log/src/main/webapp/views/member/my/myReviewList.jsp

[jji] ReviewBoard 필드명 수정 및 내가 작성한 리뷰 페이지 구현 commit

[jji] ReviewBoard 필드명 수정 및 내가 작성한 리뷰 페이지 구현 commit

---

film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardInsertServlet.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardUpdateServlet.java

[jji] 필드명 수정 commit

---

film_log/src/main/java/com/filmlog/movie/model/vo/MovieDTO.java
film_log/src/main/resources/mappers/reviewboard-mapper.xml
film_log/src/main/webapp/views/member/my/myReviewList.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardDetail.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardList.jsp

[ysw] 시간 오류 수정 commit

---

film_log/src/main/java/com/filmlog/common/vo/Paging.java
film_log/src/main/java/com/filmlog/reviewboard/controller/ReviewBoardListServlet.java
film_log/src/main/resources/mappers/reviewboard-mapper.xml
film_log/src/main/webapp/views/member/my/myReviewList.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardDetail.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardInsert.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardList.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardUpdate.jsp

[ysw] 리뷰 게시판 검색 기능 구현 및 페이징 처리 오류 처리 commit

[ysw] 리뷰 게시판 검색 기능 구현 및 페이징 처리 오류 처리 commit

---

film_log/src/main/webapp/views/reviewBoard/reviewBoardDetail.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardInsert.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardUpdate.jsp

[ysw] 글자수 제한 반영 및 댓글 오류 처리 commit

[ysw] 글자수 제한 반영 및 댓글 오류 처리 commit

---

film_log/src/main/java/com/filmlog/common/mail/EmailSender.java
film_log/src/main/java/com/filmlog/common/mail/EmailVerification.java

[jji] smtp.properties 적용

---

film_log/src/main/java/com/filmlog/member/user/controller/MonthChartServlet.java
film_log/src/main/java/com/filmlog/member/user/model/dao/WatchedMovieRecordDao.java
film_log/src/main/java/com/filmlog/member/user/model/service/WatchedMovieRecordService.java
film_log/src/main/java/com/filmlog/member/user/model/vo/MonthWatch.java
film_log/src/main/resources/mappers/watchedMovieRecord-mapper.xml
film_log/src/main/resources/mybatis-config.xml
film_log/src/main/webapp/views/member/my/dashBoard.jsp

[jhs] 차트 완료

---

film_log/src/main/resources/mappers/reviewboard-mapper.xml

[ysw]mapper 쿼리 추가 commit

---

film_log/src/main/java/com/filmlog/reviewboard/model/vo/ReviewBoard.java
film_log/src/main/resources/mappers/reviewboard-mapper.xml
film_log/src/main/webapp/index.jsp
film_log/src/main/webapp/views/reviewBoard/reviewBoardList.jsp

[ysw] 홈 화면 인기 게시글에 영화 이미지 추가 및 리뷰 게시판 css 수정 commit

[ysw] 홈 화면 인기 게시글에 영화 이미지 추가 및 리뷰 게시판 css 수정 commit

---

film_log/src/main/java/com/filmlog/member/controller/MemberInfoChangeServlet.java
film_log/src/main/webapp/views/member/my/myInfoChange.jsp

[jji] 회원수정에서 프로필 기본이미지로 변경 기능 구현 commit

[jji] 회원수정에서 프로필 기본이미지로 변경 기능 구현 commit

---

film_log/src/main/java/com/filmlog/common/mail/EmailSender.java

[jji] EmailSender 수정 commit
